spring:
  output:
    ansi:
      enabled: always

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  data:
#    mongodb:
#      host: "${MONGO_HOST}"
#      port: "${MONGO_PORT}"
#      database: chat

  datasource:
    url: "${DATABASE_URL}"
    driver-class-name: org.mariadb.jdbc.Driver
    username: "${DATABASE_ID}"
    password: "${DATABASE_PASSWORD}"

  jpa:
    open-in-view: false
    show-sql: true

  redis:
    host: "${REDIS_HOST}"
    port: "${REDIS_PORT}"
    password: "${REDIS_PASSWORD}"

  jwt:
    secret-key: "${JWT_SECRET_KEY}"

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${GOOGLE_CLIENT_ID}"
            client-secret: "${GOOGLE_CLIENT_SECRET}"
            redirect-uri: "${DOMAIN}/login/oauth2/google"
            scope:
              - email
              - profile
          naver:
            client-id: "${NAVER_CLIENT_ID}"
            client-secret: "${NAVER_CLIENT_SECRET}"
            redirect-uri: "${DOMAIN}/login/oauth2/naver"
            client-name: Naver
            authorization-grant-type: authorization_code
            scope:
              - email
              - public_profile
          kakao:
            client-id: "${KAKAO_CLIENT_ID}"
            client-secret: "${KAKAO_CLIENT_SECRET}"
            client-name: Kakao
            client-authentication-method: client_secret_post
            redirect-uri: "${DOMAIN}/login/oauth2/kakao"
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - profile_nickname

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id

springdoc:
  packages-to-scan: com.salary
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    disable-swagger-default-url: true
    path: /api-docs.html            # Swagger UI 경로 => localhost:8000/demo-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true